language: python
python:
- 3.2
- 3.3
install:
- pip install pep8
script:
- pep8 .
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
